---
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL}
sentry:
  dsn: ${SENTRY_DSN}
  enabled: ${SENTRY_ENABLED:false}
  traces-sample-rate: 1
server:
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  port: ${PORT:8080}
spring:
  application:
    name: notification-service
  management:
    tracing:
      sampling:
        probability: 1
  logging:
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      data-source-properties:
        prepareThreshold: 0
      maximum-pool-size: 5
      minimum-idle: 2
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  from-number: ${TWILIO_FROM_NUMBER}