version: 2
updates:

  # Maven dependencies for all services
  - package-ecosystem: maven
    directory: /api-gateway
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - java

  - package-ecosystem: maven
    directory: /auth-service
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - java

  - package-ecosystem: maven
    directory: /student-service
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - java

  - package-ecosystem: maven
    directory: /attendance-service
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - java

  - package-ecosystem: maven
    directory: /notification-service
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - java

  # Docker base images for all services
  - package-ecosystem: docker
    directory: /api-gateway
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /auth-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /student-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /attendance-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: /notification-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - docker