spring:
  application:
    name: attendance-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.taevafrvhdlcjulzbxnw}
    password: ${SPRING_DATASOURCE_PASSWORD:YOUR_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

server:
  port: 9092

jwt:
  secret: ${JWT_SECRET:your-super-secret-key-minimum-32-characters-long}

services:
  notification-service: ${SERVICES_NOTIFICATION_SERVICE:http://localhost:9094}

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 1.0
  enabled: ${SENTRY_ENABLED:false}