---
jwt:
  secret: ${JWT_SECRET}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - caches
  health:
    defaults:
      enabled: true
otel:
  service:
    name: ${spring.application.name}
sentry:
  dsn: ${SENTRY_DSN}
  enabled: ${SENTRY_ENABLED:false}
  traces-sample-rate: 1
server:
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  port: ${PORT:8080}
services:
  notification-service: ${SERVICES_NOTIFICATION_SERVICE:http://localhost:9094}
spring:
  application:
    name: attendance-service
#  cache:
#    type: caffeine
#    caffeine:
#      spec: maximumSize=500,expireAfterWrite=300s
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      leak-detection-threshold: 60000
      max-lifetime: 600000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: ${spring.application.name}-pool
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  logging:
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  management:
    tracing:
      sampling:
        probability: 1
  threads:
    virtual:
      enabled: true