---
jwt:
  secret: ${JWT_SECRET}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health,info,metrics,prometheus
  health:
    defaults:
      enabled: true
sentry:
  dsn: ${SENTRY_DSN}
  enabled: ${SENTRY_ENABLED:false}
  traces-sample-rate: 1
server:
  port: ${PORT:9091}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowCredentials: true
                allowedHeaders:
                  - '*'
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedOrigins:
                  - http://localhost:3000
                  - https://student-tracking-system-omega.vercel.app
          routes:
            - filters:
                - JwtAuthenticationFilter
              id: auth-service
              predicates:
                - Path=/auth/**
              uri: ${SERVICES_AUTH_SERVICE:http://localhost:9093}
            - filters:
                - JwtAuthenticationFilter
              id: user-service
              predicates:
                - Path=/users/**
              uri: ${SERVICES_AUTH_SERVICE:http://localhost:9093}
            - filters:
                - JwtAuthenticationFilter
              id: student-service
              predicates:
                - Path=/students/**
              uri: ${SERVICES_STUDENT_SERVICE:http://localhost:9095}
            - filters:
                - JwtAuthenticationFilter
              id: classes-service
              predicates:
                - Path=/classes/**
              uri: ${SERVICES_STUDENT_SERVICE:http://localhost:9095}
            - filters:
                - JwtAuthenticationFilter
              id: grades-service
              predicates:
                - Path=/grades/**
              uri: ${SERVICES_STUDENT_SERVICE:http://localhost:9095}
            - filters:
                - JwtAuthenticationFilter
              id: assignments-service
              predicates:
                - Path=/assignments/**
              uri: ${SERVICES_STUDENT_SERVICE:http://localhost:9095}
            - filters:
                - JwtAuthenticationFilter
              id: files-service
              predicates:
                - Path=/files/**
              uri: ${SERVICES_STUDENT_SERVICE:http://localhost:9095}
            - filters:
                - JwtAuthenticationFilter
              id: attendance-service
              predicates:
                - Path=/attendance/**
              uri: ${SERVICES_ATTENDANCE_SERVICE:http://localhost:9092}
            - filters:
                - JwtAuthenticationFilter
              id: notification-service
              predicates:
                - Path=/notifications/**
              uri: ${SERVICES_NOTIFICATION_SERVICE:http://localhost:9094}